osx_image: xcode7.1
language: objective-c
xcode_workspace: WordPress.xcworkspace
xcode_scheme: WordPress
xcode_sdk: iphonesimulator
notifications:
  email: true
install:
- gem install xcpretty-travis-formatter
- pod install
script:
- Scripts/build.sh
env:
  global:
    secure: Sw3dwkuh9QjVYvvxcVnVN/wHGlhGjAsJjmEfGfqKMJZusdbNCU6tIZ7nmU2cVHDhozoPG4bHK62FgOmc1PhANyEQLe7eICh+G9djr0VP6Rd4/LLbv052dqpSrshwzFLDHCUvjTfEiJsTbQeuQYX2zQqFqvxV5eOnFkMoG4vK7rQ=
