osx_image: xcode61
language: objective-c
xcode_workspace: WordPress.xcworkspace
xcode_scheme: WordPress
xcode_sdk: iphonesimulator8.1
notifications:
  email: true
before_install:
  - gem install cocoapods
